=== WemmersonAlb/xml/a3/agenda.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="agenda">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="evento" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string"/>
                            <xs:element name="hora" type="xs:string"/>
                            <xs:element name="local" type="xs:string"/>
                            <xs:element name="descricao" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="dia" type="xs:integer"/>
                        <xs:attribute name="mes" type="xs:integer"/>
                        <xs:attribute name="ano" type="xs:integer"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== WemmersonAlb/xml/a3/agenda.xml
<?xml version="1.0" encoding="UTF-8"?>
<agenda xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="agenda.xsd">
    <evento dia="01" mes="12" ano="2023">
        <titulo>Lorem Ipsum</titulo>
        <hora>08:00</hora>
        <local></local>
        <descricao>
            Lorem ipsum dolor sit amet consectetur,
            adipisicing elit. Magni voluptate dolore
            porro, ut molestias maiores, commodi aspernatur
            expedita magnam odit, dignissimos tempora neque
            nihil soluta quod accusantium aliquam assumenda
            optio?
        </descricao>
    </evento>
    <evento dia="02" mes="12" ano="2023">
        <titulo>Lorem Ipsum</titulo>
        <hora>08:00</hora>
        <local></local>
        <descricao>
            Lorem ipsum dolor sit amet consectetur,
            adipisicing elit. Magni voluptate dolore
            porro, ut molestias maiores, commodi aspernatur
            expedita magnam odit, dignissimos tempora neque
            nihil soluta quod accusantium aliquam assumenda
            optio?
        </descricao>
    </evento>
    <evento dia="03" mes="12" ano="2023">
        <titulo>Lorem Ipsum</titulo>
        <hora>08:00</hora>
        <local></local>
        <descricao>
            Lorem ipsum dolor sit amet consectetur,
            adipisicing elit. Magni voluptate dolore
            porro, ut molestias maiores, commodi aspernatur
            expedita magnam odit, dignissimos tempora neque
            nihil soluta quod accusantium aliquam assumenda
            optio?
        </descricao>
    </evento>
    <evento dia="04" mes="12" ano="2023">
        <titulo>Lorem Ipsum</titulo>
        <hora>08:00</hora>
        <local></local>
        <descricao>
            Lorem ipsum dolor sit amet consectetur,
            adipisicing elit. Magni voluptate dolore
            porro, ut molestias maiores, commodi aspernatur
            expedita magnam odit, dignissimos tempora neque
            nihil soluta quod accusantium aliquam assumenda
            optio?
        </descricao>
    </evento>
</agenda>
